services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - agenda-network

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - agenda-network

networks:
  agenda-network:
    driver: bridge
